### ISSUE TITLE
Not a valid JSON Reference for Object Array

### ISSUE THREAD

**Issue by FedeG** [Icinetic/baucis-swagger2#5]
Swagger not understand the reference to string because it is a type.
For example in the model :
`friends: [{type: ObjectId, ref: 'User' }]`

The swagger.json generated is :
``` json
"friends ": {
  "type": "array",
  "items" : {
    " $ref": "string"
}
```
(code generator : https://github.com/Icinetic/baucis-swagger2/blob/master/Controller.js#L236)
But this swagger.json is invalid.

The correct Swagger.json is:
``` json
"friends ": {
  "type": "array",
  "items": {
    "type": "string"
}
```

**Comment by pjmolina** [comment]
Thanks for reporting it. Has been fixed in v. 0.3.9  ;-)
