### ISSUE TITLE
TypeError: Cannot read property 'ref' of undefined

### ISSUE THREAD

**Issue by xx4159** [Icinetic/baucis-swagger2#7]
```
// Controller.js
function isArrayOfRefs(type) {
	return (type && type.length > 0 && type[0].ref &&
	        type[0].type && type[0].type.name === 'ObjectId');
  }
```

type[0] could be `undefined`.

so we need to check `&& type[0] `.

```
// Controller.js
function isArrayOfRefs(type) {
	return (type && type.length > 0 && type[0] && type[0].ref &&
	        type[0].type && type[0].type.name === 'ObjectId');
  }
```

**Comment by pjmolina** [comment]
Thanks @xx4159 for pointing it out.

Fixed at 0.3.17 with PR https://github.com/Icinetic/baucis-swagger2/pull/8

**Note:** As I am not longer work for Icinetic, a fork with changes is on https://github.com/pjmolina/baucis-swagger2 

Last changes also published on npm.
